language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7

install:
    - pip install tox
    - pip install tox-travis

script:
    - tox

after_success:
    - pip install python-coveralls
    - coveralls
